version: '3.7'

services:
  db:
    image: postgres:14.4-bullseye
    container_name: db_clean
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./ini/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    environment:
      - POSTGRES_USER=clean_db_user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=clean_db
    ports:
      - 5434:5432

  api:
    build: .
    container_name: fastapi_clean
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
