version: '3.7'
services:
    clean-database:
        image: postgres:latest
        environment:
          - POSTGRES_USER=root
          - POSTGRES_PASSWORD=root
          - POSTGRES_DB=BackendDP
        ports:
          - 5432:5432
        volumes:
          - ./db/postgres-data:/var/lib/postgresql/data
        networks:
          - postgres-compose-network
networks:
  postgres-compose-network:
    driver: bridge